### ISSUE TITLE
Anatomy of an HTML Element

### ISSUE THREAD

**Issue by Vertacx** [Vertacx/CO-FEB-0124-Shubasri-Frontend-Development-Upskilling#20]
An HTML element typically consists of:

1. Opening Tag
2. Content
3. Closing Tag

**Example:** `<p>Hello, world!</p>`
This HTML element is a paragraph element. Here's how it breaks down:

1. Opening Tag: <p>
2. Content: Hello, world!
3. Closing Tag: </p>

**Analogy: Think of an HTML Element as a Sandwich**

1. Opening Tag: This is like the top slice of bread in a sandwich.
2. Content: This is like the filling inside the sandwich (e.g., ham, cheese, lettuce).
3. Closing Tag: This is like the bottom slice of bread in the sandwich.
Just like a sandwich needs both slices of bread to hold the filling together, an HTML element needs both an opening and a closing tag to properly contain the content.

**Detailed Breakdown**

- Opening Tag

    The opening tag tells the browser where the element begins.
    It's enclosed in angle brackets (< >).
    The name of the element is inside the brackets (e.g., p for paragraph).

- Content
    The content is the actual text or other HTML elements that the tag is wrapping around.
    In our example, the content is Hello, world!.

- Closing Tag

    The closing tag tells the browser where the element ends.
    It's also enclosed in angle brackets but has a forward slash (/) before the element name (e.g., </p> for paragraph).

**More Examples**
**Example 1: Header Element**

`<h1> Welcome to my website! </h1>`

    Opening Tag: <h1>
    Content: Welcome to My Website
    Closing Tag: </h1>

**Example 2: Anchor (Link) Element**
`<a href="https://www.example.com">Example Website</a> `

    Opening Tag: <a href="https://www.example.com">
    Content: Click here to visit Example
    Closing Tag: </a>

**Explanation of Anchor Element**
    The anchor element (<a>) is used to create hyperlinks.
    It includes an attribute (href="https://www.example.com") inside the opening tag, which specifies the URL the link points to.
    The content (Click here to visit Example) is the clickable text.
    The closing tag (</a>) ends the anchor element.
    
**Special Case: Self-Closing Tags or Void Elements**

Some HTML elements don't have any content and are self-closing. These tags look slightly different.
    
`<img src="https://www.example.com/image.jpg" alt="Example Image" />`

  Self-Closing Tag: <img src="https://www.example.com/image.jpg" alt="Description of the image" /> 
  
  Trivia: Do you know why the image is broken? Comment your answers in the comment section
  
  The img tag is self-closing because images don't need closing tags. Instead, the / at the end indicates it's a self-contained element.

Video Link 
[Tag structure](https://youtu.be/hfFnMvXjTMI)

**Comment by subhasri0206** [comment]
The image is broken due to the following:
1. Incorrect file path
2. Broken URL
