### ISSUE TITLE
Activity: Replicate the layout using <div> elements.

### ISSUE THREAD

**Issue by Vertacx** [Vertacx/CO-FEB-0124-Shubasri-Frontend-Development-Upskilling#55]
### **Activity: Replicate the Layout Using `<div>` Elements**

**Step 1: Analyze the Layout**
- Look at the original layout you want to replicate. Identify the different sections (e.g., header, main content, sidebar, footer) and how they are arranged.

**Step 2: Set Up Your HTML File**
- Create a new HTML file (e.g., `index.html`) in your project directory.

**Step 3: Structure the HTML with `<div>` Elements**
- Open your HTML file and start by adding the basic HTML structure:
- Add `<div>` elements to represent different sections of the layout:

**Step 4: Style Your Layout**
- Create a CSS file (e.g., `styles.css`) and link it to your HTML file.
- In your CSS file, add styles to position and format your `<div>` elements according to the layout you are replicating:

**Step 5: Test and Adjust**
- Open your HTML file in a web browser and check how the layout looks.
- Adjust the CSS styles as needed to match the original layout more closely.

**Step 6: Review and Refine**
- Make sure all sections are correctly styled and positioned.

### Layout 1:
![image (1)](https://github.com/user-attachments/assets/c955348f-c4b0-4f35-abf3-b9c64d96ba2c)

### Layout 2:
![image](https://github.com/user-attachments/assets/97fab13a-2167-4240-b92c-8f73118a3bb4)
### Layout 3:
![DIv3](https://github.com/user-attachments/assets/66531ff0-f95b-486c-8657-28aa23f8478c)

**Comment by subhasri0206** [comment]
**Layout 1 - HTML**

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="An example layout 1." />
    <meta name="keywords" content="HTML, head tag, meta tags, web development" />
    <meta name="author" content="XXX" />
    <title>HTML Layout 1</title>
    <link rel="stylesheet" href="style.css" />
    <meta property="og:title" content="HTML Layout 1" />
    <meta property="og:url" content="http://www.layout1.com" />
    <meta property="og:image" content="http://layout1.jpg" />
    <meta property="og:description" content="An example layout 1." />
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Advanced Semantic HTML</h1>
            <nav>
                <a href="#" class="nav-link">Home</a>
                <a href="#" class="nav-link">Services</a>
                <a href="#" class="nav-link">About</a>
                <a href="#" class="nav-link">Contact</a>
            </nav>
        </div>
        <div class="main">
            <h2>Welcome to Our Website</h2>
            <hr>
            <p>This is an example of an advanced semantic HTML page.</p>
        </div>
        <div class="services">
            <h2>Our Services</h2>
            <hr>
            <div class="sub-service">
                <h3>Web Development</h3>
                <p>We offer comprehensive web development services.</p>
            </div>
            <div class="sub-service">
                <h3>SEO Optimization</h3>
                <p>Improve your website's search engine ranking.</p>
            </div>
        </div>
        <div class="contact">
            <h2>Contact Us</h2>
            <hr>
            <p><i>1234 Elm Street <br> Springfield, IL 63701</i></p>
        </div>    
        <div class="footer">
            <p>&copy; 2024 Advanced Semantic HTML. All rights reserved.</p>
        </div>
    </div>
</body>
</html>`

**Layout 1 - CSS**

`body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
}
.container {
    padding: 0;
}
.header {
    background-color: #333;
    color: #fff;
    padding: 10px;
    text-align: center;
}
.nav-link {
    color: #fff;
    text-decoration: none;
    margin: 10px;
}
hr {
    border: 1px solid #1045c1;
}
.main {
    background-color: #fff;
    padding: 20px 20px 5px 20px; /* top right bottom left */
}
.services {
    background-color: #fff;
    padding: 5px 20px 5px 20px; 
}
.sub-service {
    border: 1px solid #807f7e65;
    margin: 0px 0px 10px 0px;
    padding: 20px;
    border-radius: 5px;
}
.contact {
    background-color: #fff;
    padding: 5px 20px 5px 20px;
}
.contact p {
    border: 1px solid #807f7e65;
    margin-left: 0px 0px 10px 0px;
    padding: 20px;
    border-radius: 5px;
}
.footer {
    background-color: #333;
    color: #fff;
    padding: 20px;
    text-align: center;
}`

![Image](https://github.com/user-attachments/assets/eddda58c-a6d7-452b-a8ed-5aa271137f08)

**Comment by subhasri0206** [comment]
**Layout 2 - HTML**

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="An example layout 2." />
    <meta name="keywords" content="HTML, head tag, meta tags, web development" />
    <meta name="author" content="XXX" />
    <title>HTML Layout 2</title>
    <link rel="stylesheet" href="style.css" />
    <meta property="og:title" content="HTML Layout 2" />
    <meta property="og:url" content="http://www.layout2.com" />
    <meta property="og:image" content="http://layout2.jpg" />
    <meta property="og:description" content="An example layout 2." />
</head>
<body>
    <div class="container">
        <h1>Simple HTML Form</h1>
        <div class="form">
            <div class="field">Name:</div>
            <div class="value">Enter your name</div>
        </div>
        <div class="form">
            <div class="field">Email:</div>
            <div class="value">Enter your email</div>
        </div>
        <div class="form">
            <div class="field">Message:</div>
            <div class="value">Enter your message</div>
        </div>
        <div class="form">
            <div class="field">Country:</div>
            <div class="value">Enter your country</div>
        </div>
        <div class="form">
            <div class="button">Submit</div>
        </div>
    </div>
</body>
</html>`

**Layout 2 - CSS**

`body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
}
.container {
    width: 500px;
    margin: 50px auto;
    padding: 20px;
    background-color: #ffffff;
    border-radius: 5px;
}
.form {
    margin-bottom: 20px;
}
.field {
    font-weight: bold;
    margin-bottom: 5px;
}
.value {
    padding: 10px;
    border: 1px solid #504d4d;
    border-radius: 3px;
}
.button {
    background-color: #4CAF50;
    color: white;
    padding: 10px 20px;
    text-align: center;
    width: 50px;
    border-radius: 5px;
}`

![Image](https://github.com/user-attachments/assets/d81622b0-c87d-4dc5-bc0a-d25d657e4b2c)

**Comment by subhasri0206** [comment]
**Layout 3 - HTML**

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="An example layout 3." />
    <meta name="keywords" content="HTML, head tag, meta tags, web development" />
    <meta name="author" content="XXX" />
    <title>HTML Layout 3</title>
    <link rel="stylesheet" href="style.css" />
    <meta property="og:title" content="HTML Layout 3" />
    <meta property="og:url" content="http://www.layout3.com" />
    <meta property="og:image" content="http://layout3.jpg" />
    <meta property="og:description" content="An example layout 3." />
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Welcome To My Sample Webpage</h1>
            <nav>
                <a href="#" class="nav-link">Home</a>
                <a href="#" class="nav-link">Services</a>
                <a href="#" class="nav-link">About</a>
                <a href="#" class="nav-link">Contact</a>
            </nav>
        </div>
        <div class="content">
            <div class="section">
                <h2>About Us</h2>
                <p>Welcome to our website! We are dedicated to providing top-quality services to our clients. Our team of professionals is committed to excellence and ensuring customer satisfaction in all we do.</p>
            </div>
            <div class="section">
                <h2>Our Services</h2>
                <div class="services-box">
                    <div class="image"></div>
                    <p>Our excellent services.</p>
                </div>
                <p>We offer a wide range of services to meet your needs, including:</p>
                <h3>Service Breakdown</h3>
                <ul>
                    <li>
                        <h4>Consulting</h4>
                        <ul>
                            <li>Business Strategy
                                <ul>
                                    <li>Market Analysis - Detailed analysis of market trends and opportunities.</li>
                                    <li>Strategic Planning - Formulating effective strategies for business growth.</li>
                                </ul>
                            </li>
                            <li>Technology
                                <ul>
                                    <li>IT Infrastructure - Setting up robust IT systems and networks.</li>
                                    <li>Software Development - Custom software solutions to meet your business needs.</li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <h4>Marketing</h4>
                        <ul>
                            <li>Digital Marketing
                                <ul>
                                    <li>SEO - Optimizing your website for search engines.</li>
                                    <li>Social Media Management - Managing and growing your social media presence.</li>
                                </ul>
                            </li>
                            <li>Content Creation
                                <ul>
                                    <li>Copywriting - Creating compelling written content.</li>
                                    <li>Graphic Design - Designing visually appealing graphics.</li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="section">
                <h2>Contact Information</h2>
                <p>If you have any questions or would like to get in touch with us, please use the contact information below:</p>
                <div class="contact-info">
                    <div class="info-row">
                        <div class="info-label">Contact Type</div>
                        <div class="info-value">Details</div>
                    </div>
                    <div class="info-row">
                        <div class="info-label">Email</div>
                        <div class="info-value">info@example.com</div>
                    </div>
                    <div class="info-row">
                        <div class="info-label">Phone</div>
                        <div class="info-value">+123456789</div>
                    </div>
                    <div class="info-row">
                        <div class="info-label">Address</div>
                        <div class="info-value">123 Sample Street, Sample City, Country</div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer">
            <p>© 2024 Sample Webpage. All rights reserved.</p>
        </div>
    </div>
</body>
</html>`

**Layout 3 - CSS**

`body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
}
.container {
    padding: 0px;
}
.header {
    background-color: #333;
    color: #fff;
    padding: 10px;
    text-align: center;
}
.nav-link {
    color: #fff;
    text-decoration: none;
    margin: 10px;
}
.content {
    padding: 20px;
}
.services-box {
    margin-left: auto;
    margin-right: auto;
    width: 50%;
    text-align: center;
}
.image {
    width: 400px;
    height: 400px;
    background-color: #eee;
    margin-left: auto;
    margin-right: auto;
}
.info-label {
    float: left;
    width: 30%;
    margin-bottom: 10px;
}
.info-value {
    float: right;
    width: 70%;
    margin-bottom: 10px;
}
.footer {
    background-color: #333;
    color: #fff;
    margin-top: 90px;
    padding: 10px;
    text-align: center;
}`

![Image](https://github.com/user-attachments/assets/b7fd8103-c253-4e9c-9ae4-27f29cfa7762)

**Comment by subhasri0206** [comment]
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="An example layout 4." />
    <meta name="keywords" content="HTML, head tag, meta tags, web development" />
    <meta name="author" content="XXX" />
    <title>HTML Layout 4</title>
    <link rel="stylesheet" href="style.css" />
    <meta property="og:title" content="HTML Layout 4" />
    <meta property="og:url" content="http://www.layout4.com" />
    <meta property="og:image" content="http://layout4.jpg" />
    <meta property="og:description" content="An example layout 4." />
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Welcome!</h1>
            <nav>
                <a href="#" class="nav-link">Home</a>
                <a href="#" class="nav-link">Services</a>
                <a href="#" class="nav-link">About</a>
                <a href="#" class="nav-link">Contact</a>
            </nav>
        </div>
        <div class="sidebar">
            <h2>Latest News</h2>
            <ul>
                <li><a href="#">News 1</a></li>
                <li><a href="#">News 2</a></li>
                <li><a href="#">News 3</a></li>
            </ul>
        </div>
        <div class="content">
            <h1>Article Acceleration</h1>
            <p>This is a simple webpage where you can find interesting articles.</p>
            <div class="article1">
                <h2>Article 1</h2>
                <p>Artificial Intelligence is transforming healthcare by improving diagnostics and patient care. Hospitals are adopting AI-driven tools to enhance treatment accuracy and efficiency.</p>
            </div>
            <div class="article2">
                <h2>Article 2</h2>
                <p>Blockchain technology is expanding beyond cryptocurrency applications, revolutionizing supply chain management. Companies are leveraging blockchain for enhanced transparency and security.</p>
            </div>
        </div>
        <div class="footer">
            <p>Copyright © 2023</p>
        </div>
    </div>
</body>
</html>`

**Layout 4 - CSS**

`body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
}
.container {
    padding: 0px;
}
.header {
    background-color: #5c3958;
    color: #fff;
    padding: 10px;
    text-align: center;
}
.nav-link {
    color: #fff;
    text-decoration: none;
    margin: 10px;
}
.sidebar {
    margin: 20px;
    padding: 20px;
    background-color: #f7f7f7;
    border: 1px solid #ddd;
}
.sidebar li {
    margin-bottom: 10px;
}
.sidebar a {
    text-decoration: none;
}
.content {
    padding: 20px;
}
.article1, .article2 {
    margin-bottom: 20px;
    padding: 20px;
    background-color: #f7f7f7;
    border: 1px solid #ddd;
}
.footer {
    background-color: #5c3958;
    color: #fff;
    padding: 10px;
    text-align: center;
}

```
